### ISSUE TITLE
ERROR: Layer 'val_transform' references bottom 'label' at the TEST stage however this blob is not included at that stage. 

### ISSUE THREAD

**Issue by 00krishna** [allykgray/DetectionTutorialSpaceNet#2]
Hello. I tried to implement the Caffe model as specified in the repo, but I am getting the following error when I implement the model in DIGITS. Here is the record from the log file. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/digits/scheduler.py", line 512, in run_task
    task.run(resources)
  File "/usr/local/lib/python2.7/dist-packages/digits/task.py", line 189, in run
    self.before_run()
  File "/usr/local/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 220, in before_run
    self.save_files_generic()
  File "/usr/local/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 734, in save_files_generic
    CaffeTrainTask.net_sanity_check(deploy_network, caffe_pb2.TEST)
  File "/usr/local/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 1654, in net_sanity_check
    "TRAIN" if phase == caffe_pb2.TRAIN else "TEST"
CaffeTrainSanityCheckError: Layer 'val_transform' references bottom 'label' at the TEST stage however this blob is not included at that stage. Please consider using an include directive to limit the scope of this layer.
```
This error seems related to this particular section of the caffe model, below. Not sure what is causing, the error. Could it be related to the name "label" versus perhaps "val_label" or something? 

Any suggestions would be appreciated.

```
layer {
  name: "val_transform"
  type: "DetectNetTransformation"
  bottom: "data"
  bottom: "label"
  top: "transformed_data"
  top: "transformed_label"
  include {
    phase: TEST
  }
  transform_param {
    mean_value: 127.0
  }
  detectnet_groundtruth_param {
    stride: 16
    scale_cvg: 0.4
    gridbox_type: GRIDBOX_MIN
    min_cvg_len: 20
    coverage_type: RECTANGULAR
    image_size_x: 1280
    image_size_y: 1280
    obj_norm: true
    crop_bboxes: false
  }
}
```

**Comment by mantianwuming** [comment]
Hello, I meet the same problem and have you solved it yet?
